# Urllib connects to a wrong host

## Report Details
- **Report ID**: 305978
- **URL**: https://hackerone.com/reports/305978
- **State**: Closed
- **Severity**: low
- **Submitted**: 2018-01-17T17:42:47.877Z
- **Disclosed**: 2019-11-12T09:00:41.456Z

## Reporter
- **Username**: orange
- **Name**: N/A

## Team
- **Name**: N/A
- **Handle**: ibb

## Vulnerability Information
## Description
-----
The inconsistent of URL parsing and URL fetching are distinct


　
## Original bug report
-----
- https://bugs.python.org/issue30500
- http://python-security.readthedocs.io/vuln/bpo-30500_urllib_connects_to_a_wrong_host.html

　
## Note
-----
- None

　
Thanks :)

## Impact

SSRF

## Attachments
No attachments
